###Auth - Fazer Login
POST http://localhost:1337/api/auth/login
Content-Type: application/json

{
  "identifier": "visao@email.com",
  "password": "senha123"
}

### Auth - registro
POST http://localhost:1337/api/auth/register
Content-Type: application/json

{
  "username": "heloisa",
  "email": "heloisa@email.com",
  "password": "senha123"
}
