###Auth - Fazer Login como tutor
POST http://localhost:1337/api/auth/login
Content-Type: application/json

{
  "identifier": "juliana@email.com",
  "password": "senha123"
}

###Auth - Fazer Login como catsitter
POST http://localhost:1337/api/auth/login
Content-Type: application/json

{
  "identifier": "heloisa@email.com",
  "password": "senha123"
}

### Auth - registro
POST http://localhost:1337/api/auth/register
Content-Type: application/json

{
  "username": "Luciana",
  "email": "luciana@email.com",
  "password": "senha123",
  "role": "TUTOR"
}

### Gatos - Ver todos os MEUS gatos - TUTOR
GET http://localhost:1337/api/gatos/meus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4
### Gatos - Ver todos os gatos disponiveis - CATSITTER
GET http://localhost:1337/api/gatos/disponiveis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiaGVsb2lzYUBlbWFpbC5jb20iLCJyb2xlIjoiQ0FUU0lUVEVSIiwiaWF0IjoxNzg5MTI4OTE2LCJleHAiOjE3ODk3MzM3MTZ9.t4h34XvUKI7-cApHqkkdEBxUGic9RDFhZgzNC69XHY8
### Gatos - Buscar por nome do gato em gatos disponiveis - CATSITTER

GET http://localhost:1337/api/gatos/disponiveis?searchGato=mingau
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiaGVsb2lzYUBlbWFpbC5jb20iLCJyb2xlIjoiQ0FUU0lUVEVSIiwiaWF0IjoxNzg5MTI4OTE2LCJleHAiOjE3ODk3MzM3MTZ9.t4h34XvUKI7-cApHqkkdEBxUGic9RDFhZgzNC69XHY8

### Gatos - Buscar por nome do gato em MEUS gatos - TUTOR
GET http://localhost:1337/api/gatos/meus?searchGato=susie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4
### Gatos - Buscar por nome do tutor em gatos disponiveis - CATSITTER
GET http://localhost:1337/api/gatos/disponiveis?searchTutor=pedro
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiaGVsb2lzYUBlbWFpbC5jb20iLCJyb2xlIjoiQ0FUU0lUVEVSIiwiaWF0IjoxNzg5MTI4OTE2LCJleHAiOjE3ODk3MzM3MTZ9.t4h34XvUKI7-cApHqkkdEBxUGic9RDFhZgzNC69XHY8

### Gatos - Buscar por nome do gato e tutor em gatos disponiveis - CATSITTER
GET http://localhost:1337/api/gatos/disponiveis?searchGato=thor&searchTutor=pedro
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiaGVsb2lzYUBlbWFpbC5jb20iLCJyb2xlIjoiQ0FUU0lUVEVSIiwiaWF0IjoxNzg5MTI4OTE2LCJleHAiOjE3ODk3MzM3MTZ9.t4h34XvUKI7-cApHqkkdEBxUGic9RDFhZgzNC69XHY8


### Gatos - salvar um novo gato - TUTOR
POST http://localhost:1337/api/gatos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4


{
  "nomeGato": "Michael Jackson",
  "idadeGato": 2,
  "pesoGato": 4.5,
  "peloGato": 2,
  "racaGato": "Sem Raça Definida",
  "idIcone": 5
}

### Gatos - atualizar informações de um gato - TUTOR
PUT http://localhost:1337/api/gatos/65f1a0020000000000000007
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4

{
  "peloGato": 3,
  "idIcone": 2,
  "disponivel_para_cuidado": 0
}

### Tarefas - visualizar uma lista de tarefas de um gato especifico - TUTOR
GET http://localhost:1337/api/tarefas/65f1a0020000000000000007
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4
### Tarefas - visualizar uma lista de tarefas de um gato especifico - CATSITTER
GET http://localhost:1337/api/tarefas/65f1a0020000000000000007
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiaGVsb2lzYUBlbWFpbC5jb20iLCJyb2xlIjoiQ0FUU0lUVEVSIiwiaWF0IjoxNzg5MTI4OTE2LCJleHAiOjE3ODk3MzM3MTZ9.t4h34XvUKI7-cApHqkkdEBxUGic9RDFhZgzNC69XHY8

### Tarefas - criar uma tarefa para um gato especifico - TUTOR
POST http://localhost:1337/api/tarefas/tarefa/65f1a0020000000000000007
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4

{
  "descricao": "Dar banho no gato",
  "pontos": 10
}

### Tarefas - deletar uma tarefa especifica de um gato especifico - TUTOR
DELETE http://localhost:1337/api/tarefas/tarefa/65f1a0020000000000000007/6aa3f1fc0432d8a85639d834
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4
### Tarefas - atualizar uma tarefa especifica de um gato especifico - TUTOR
PUT http://localhost:1337/api/tarefas/tarefa/65f1a0020000000000000007/65f1a0030000000000000012
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMiIsImVtYWlsIjoianVsaWFuYUBlbWFpbC5jb20iLCJyb2xlIjoiVFVUT1IiLCJpYXQiOjE3ODkxMjg4NTgsImV4cCI6MTc4OTczMzY1OH0.FEKcLhfw9mRNqNN-LPqJet5VywNMupdJWD_JYpYAVU4

{
  "descricao": "Dar banho no gato",
  "pontos": 15
}

### Tarefas - atualizar o status de tarefa especifica de um gato especifico - CATSITTER
PUT http://localhost:1337/api/tarefas/tarefa/65f1a0020000000000000007/65f1a0030000000000000012
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjFhMDAxMDAwMDAwMDAwMDAwMDAwMSIsImVtYWlsIjoiaGVsb2lzYUBlbWFpbC5jb20iLCJyb2xlIjoiQ0FUU0lUVEVSIiwiaWF0IjoxNzg5MTI4OTE2LCJleHAiOjE3ODk3MzM3MTZ9.t4h34XvUKI7-cApHqkkdEBxUGic9RDFhZgzNC69XHY8

