###Auth - Fazer Login como tutor
POST http://localhost:1337/api/auth/login
Content-Type: application/json

{
  "identifier": "juliana@email.com",
  "password": "senha123"
}

###Auth - Fazer Login como catsitter
POST http://localhost:1337/api/auth/login
Content-Type: application/json

{
  "identifier": "heloisa@email.com",
  "password": "senha123"
}

### Auth - registro
POST http://localhost:1337/api/auth/register
Content-Type: application/json

{
  "username": "Luciana",
  "email": "luciana@email.com",
  "password": "senha123",
  "role": "CATSITTER"
}

### Gatos - Ver todos os MEUS gatos - TUTOR
GET http://localhost:1337/api/gatos/meus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c

### Gatos - Ver todos os gatos disponiveis - CATSITTER
GET http://localhost:1337/api/gatos/disponiveis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxvaXNhQGVtYWlsLmNvbSIsInJvbGUiOiJDQVRTSVRURVIiLCJpYXQiOjE3ODYwMTQzODcsImV4cCI6MTc4NjYxOTE4N30.ysEnOCkeP2pAQZFMZbQynmh00vCgkaf6VmkawU7dm24
### Gatos - Buscar por nome do gato em gatos disponiveis - CATSITTER

GET http://localhost:1337/api/gatos/disponiveis?searchGato=mingau
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxvaXNhQGVtYWlsLmNvbSIsInJvbGUiOiJDQVRTSVRURVIiLCJpYXQiOjE3ODYwMTQzODcsImV4cCI6MTc4NjYxOTE4N30.ysEnOCkeP2pAQZFMZbQynmh00vCgkaf6VmkawU7dm24

### Gatos - Buscar por nome do gato em MEUS gatos - TUTOR
GET http://localhost:1337/api/gatos/meus?searchGato=mingau
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c

### Gatos - Buscar por nome do tutor em gatos disponiveis - CATSITTER
GET http://localhost:1337/api/gatos/disponiveis?searchTutor=pedro
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxvaXNhQGVtYWlsLmNvbSIsInJvbGUiOiJDQVRTSVRURVIiLCJpYXQiOjE3ODYwMTQzODcsImV4cCI6MTc4NjYxOTE4N30.ysEnOCkeP2pAQZFMZbQynmh00vCgkaf6VmkawU7dm24

### Gatos - Buscar por nome do gato e tutor em gatos disponiveis - CATSITTER
GET http://localhost:1337/api/gatos/disponiveis?searchGato=thor&searchTutor=pedro
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxvaXNhQGVtYWlsLmNvbSIsInJvbGUiOiJDQVRTSVRURVIiLCJpYXQiOjE3ODYwMTQzODcsImV4cCI6MTc4NjYxOTE4N30.ysEnOCkeP2pAQZFMZbQynmh00vCgkaf6VmkawU7dm24


### Gatos - salvar um novo gato - TUTOR
POST http://localhost:1337/api/gatos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c


{
  "nomeGato": "Sullie",
  "idadeGato": 2,
  "pesoGato": 4.5,
  "peloGato": 2,
  "racaGato": "Sem Raça Definida",
  "idIcone": 1
}

### Gatos - atualizar informações de um gato - TUTOR
PUT http://localhost:1337/api/gatos/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c

{
  "peloGato": 3,
  "idIcone": 2,
  "disponivel_para_cuidado": 0
}

### Tarefas - visualizar uma lista de tarefas de um gato especifico - TUTOR
GET http://localhost:1337/api/tarefas/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c

### Tarefas - visualizar uma lista de tarefas de um gato especifico - CATSITTER
GET http://localhost:1337/api/tarefas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxvaXNhQGVtYWlsLmNvbSIsInJvbGUiOiJDQVRTSVRURVIiLCJpYXQiOjE3ODYwMTQzODcsImV4cCI6MTc4NjYxOTE4N30.ysEnOCkeP2pAQZFMZbQynmh00vCgkaf6VmkawU7dm24

### Tarefas - criar uma tarefa para um gato especifico - TUTOR
POST http://localhost:1337/api/tarefas/tarefa/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c

{
  "descricao": "Dar banho no gato",
  "pontos": 10
}

### Tarefas - deletar uma tarefa especifica de um gato especifico - TUTOR
DELETE http://localhost:1337/api/tarefas/tarefa/1/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c

### Tarefas - atualizar uma tarefa especifica de um gato especifico - TUTOR
PUT http://localhost:1337/api/tarefas/tarefa/4/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqdWxpYW5hQGVtYWlsLmNvbSIsInJvbGUiOiJUVVRPUiIsImlhdCI6MTc4NjAxMzA1NiwiZXhwIjoxNzg2NjE3ODU2fQ.CtcqWRkuJhCCJet4uCW4jETKLOcrECihg8CRlFhB87c

{
  "descricao": "Dar banho no gato",
  "pontos": 15
}

### Tarefas - atualizar o status de tarefa especifica de um gato especifico - CATSITTER
PUT http://localhost:1337/api/tarefas/tarefa/4/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJoZWxvaXNhQGVtYWlsLmNvbSIsInJvbGUiOiJDQVRTSVRURVIiLCJpYXQiOjE3ODYwMTQzODcsImV4cCI6MTc4NjYxOTE4N30.ysEnOCkeP2pAQZFMZbQynmh00vCgkaf6VmkawU7dm24

